name: MineResetLite
version: 0.4.1
main: com.koletar.jj.mineresetlite.MineResetLite
author: VirtualByte
description: A lightweight solution for Mine management.
softdepend: [WorldEdit, Multiverse-Core]
commands:
  mineresetlite:
    aliases: [mrl, mr, mine, minereset]
    description: Manage mines.